### ISSUE TITLE
booleanを利用するときは少し注意しましょう

### ISSUE THREAD

**Issue by nmbakfm** [YamajiTomoya/BlogSystem#11]
open_flgなど、booleanを利用するときには注意した上で使いましょう。

今回は、公開・非公開だけの2つのステータスになりますが、例えば、「限定公開・下書き・終了」などのステータスが入ってくる可能性があります。その場合は、フラグではなく、integer型などで公開ステータスを持つ必要があります。

意識した上で、booleanを選択していれば、問題ないです。
個人的に将来的に起こりうるステータスは他にないのか？とかを考えていくと多くのケースでbooleanでは不足するイメージがあります。

**Comment by YamajiTomoya** [comment]
なるほど。。。
今回の仕様上はパラメータは２つですが、将来性を考えてintegerで持ち直すことにします。

**Comment by YamajiTomoya** [comment]
修正いたしました！

**Comment by nmbakfm** [comment]
integerにするときはenumを使うと便利です。
例えば、
`@article.status == 20`という条件式が `@article.unpublished?`などのように呼び出せます。

enumをキーワードに調べてみてください。

**Comment by YamajiTomoya** [comment]
修正いたしました！
https://github.com/YamajiTomoya/BlogSystem/commit/3e0b7d063be9de2a1d5e8c0b1b192ace4fbd8935

**Comment by nmbakfm** [comment]
okです
