### ISSUE TITLE
migrationファイルの履歴上はarticlesテーブルにauthorが存在するように見えますが、schema.rbにはauthorが存在しません。

### ISSUE THREAD

**Issue by nmbakfm** [YamajiTomoya/BlogSystem#12]
どのようにデータベースは作成・変更しましたか？
必ず、migrationファイルを経由して、作成・変更するようにしないと、
複数人で開発するときに開発環境が揃わないことがあります。

**Comment by nmbakfm** [comment]
一旦、現状のmigrationの状態にするときは`bundle exec rails db:migrate:reset`で、データベースを削除した上で、作り直してくれます。

**Comment by YamajiTomoya** [comment]
なるほど気をつけます。

**Comment by YamajiTomoya** [comment]
修正いたしました！

**Comment by nmbakfm** [comment]
OKです。
