### ISSUE TITLE
has_manyのdependentについて理解できていますか？

### ISSUE THREAD

**Issue by nmbakfm** [YamajiTomoya/BlogSystem#13]
単に質問です。

- dependentオプションとはなにか？が理解できていますか？
- `dependent: :destroy`と`dependent: :delete_all`の違いはわかりますか？

**Comment by YamajiTomoya** [comment]
・dependentオプションとはなにか？
　→自分になにかあったら、子もつられてなにか起きる、と認識しています。

・`dependent: :destroy`と`dependent: :delete_all`の違い
    →これについては昼休みに一八くんに教えてもらいました。`:destroy`が逐一モデルの`destroy`メソッドを呼ぶのに対して、`:delete_all`が、全てを削除するsql文を実行する、みたいな感じだったと思います。`:delete_all`の方は`destroy`をトリガーとする動きに着火できないので、基本は`:destroy`を使っておくべき、だったと思います。

修正しておきますね。

**Comment by nmbakfm** [comment]
OKです。
