### ISSUE TITLE
タイトルには<h*>タグを利用しましょう

### ISSUE THREAD

**Issue by nmbakfm** [YamajiTomoya/BlogSystem#15]
`<h1>`や`<h2>`などのように見出しを表すもので、タイトルは記述しましょう。
`<p>`タグ(paragraph)は段落を表すものです。

**Comment by YamajiTomoya** [comment]
修正しました！
タイトルが必要そうな所にはついてると思います。

**Comment by nmbakfm** [comment]
OKです
