### ISSUE TITLE
メソッドを使ってパスを生成しましょう

### ISSUE THREAD

**Issue by Kta-M** [YamajiTomoya/BlogSystem#16]
いろんなところにパスを直書きしてるけど、メソッドを使いましょう。
`bundle exec rails routes`でrouteのリストが出てくるけど、prefixの項目に`_path`をくっつけたメソッドでパスが取れます。パラメーターを引数を設定できたりも。

#9 に対応したあとの方がいいかも。

**Comment by YamajiTomoya** [comment]
修正いたしました！

**Comment by Kta-M** [comment]
👍
