### ISSUE TITLE
rootページをログインページにしましょう。

### ISSUE THREAD

**Issue by Kta-M** [YamajiTomoya/BlogSystem#17]
Yay! You’re on Rails!って言われたので。
これも`routes.rb`案件。

**Comment by YamajiTomoya** [comment]
修正いたしました！

**Comment by YamajiTomoya** [comment]
これですが、現在はuser/indexをログインページにして、ログイン・非ログインによってログインページとマイページに振り分けるような実装にしています。

**Comment by Kta-M** [comment]
👍
