### ISSUE TITLE
不要なファイルは消しとくといいと思う。

### ISSUE THREAD

**Issue by Kta-M** [YamajiTomoya/BlogSystem#18]
jsとか、testのファイルとか、helperとか。
rails g なんちゃらで自動生成されたものだと思うけど、空ののファイルが増えても邪魔なだけなので。必要になったら作りましょう。

**Comment by YamajiTomoya** [comment]
修正いたしました！
https://github.com/YamajiTomoya/BlogSystem/commit/69f31fdf809cc2172c8f85b30bfe3a13ed77aa1b

**Comment by YamajiTomoya** [comment]
どうやら消してはいけないものまで消してしまったようなので、戻しました。
https://github.com/YamajiTomoya/BlogSystem/commit/80ab05a521b6c9bd0e637dedf791437ae5d49286

**Comment by Kta-M** [comment]
👍
