### ISSUE TITLE
i18nを使ってみて！

### ISSUE THREAD

**Issue by Kta-M** [YamajiTomoya/BlogSystem#19]
余力があれば、メッセージとかリンクとかの文言を直書きしてるけど、i18nを使ってみましょう。
多言語化対応用の仕組みではあるけど、システム全体で用語とかを統一できたりするので、日本語だけのシステムでも使っておくと吉。

**Comment by YamajiTomoya** [comment]
修正いたしました！

**Comment by Kta-M** [comment]
なんかまだ結構残ってるような…。

**Comment by YamajiTomoya** [comment]
多分勘違いしてました。
i18nでメッセージを定義しておいて、それを呼び出す感じですね。

**Comment by YamajiTomoya** [comment]
修正いたしました！
https://github.com/YamajiTomoya/BlogSystem/commit/ac887e805b962c818fdc73a22369ee716fc4f83a

**Comment by YamajiTomoya** [comment]
すみません。
昨日の最後１つ残った適用されない問題が解決した勢いのままに報告しましたが、地域取得等がまだでした。修正してきます。

**Comment by YamajiTomoya** [comment]
修正いたしました！
https://github.com/YamajiTomoya/BlogSystem/commit/8e33703745fdb9cfc78033231ca73f9cf57a7bcd

**Comment by Kta-M** [comment]
んー、今回はこれでも大丈夫と思います。
ただ、I18nファイル、追加分は全部フラットにおいてるので、階層付けたほうが管理がしやすそう。
もしこれが複数人でやる大きめなプロジェクトだったら管理が難しくなって破綻するかも。

**Comment by YamajiTomoya** [comment]
かしこまりました。何かうまいまとめ方が思いついたらまたやってみます。

**Comment by Kta-M** [comment]
一旦閉じますー。
