### ISSUE TITLE
ArticlesController#showのdeletable_flagsの実装はArticleに持っていくほうがいいと思います

### ISSUE THREAD

**Issue by nmbakfm** [YamajiTomoya/BlogSystem#2]
`comment.deletable?(@current_user)`

みたいに呼び出せるほうがわかりやすいね。

**Comment by YamajiTomoya** [comment]
article_controllerと勘違いしました。再修正します。

**Comment by YamajiTomoya** [comment]
これですが、commentから呼んでるのでCommentモデルの関数として定義してあげるのが適当なのかなと考えましたがいかがでしょうか？

**Comment by nmbakfm** [comment]
見ました。OKです。
