### ISSUE TITLE
html.erbでのコメントには <%# ... %>を使いましょう。

### ISSUE THREAD

**Issue by Kta-M** [YamajiTomoya/BlogSystem#20]
html的には、コメントは `<!-- ... -->`だけど、これはユーザーに見えちゃいます。
html.erb上では、 <%# ... %>にしておくとrubyのコメントとして扱ってくれるので、
htmlを生成したときに無かったコトにしてくれます。

**Comment by YamajiTomoya** [comment]
修正いたしました！

**Comment by Kta-M** [comment]
👍
