### ISSUE TITLE
コードを整形しましょう

### ISSUE THREAD

**Issue by Kta-M** [YamajiTomoya/BlogSystem#21]
ところどころインデントがおかしかったり、全角スペースが含まれていたりします。
エディタにそういうのしっかりしてくれるプラグインを入れるといいかも。

**Comment by Kta-M** [comment]
あ、rubyは一般的にインデントは半角スペース2つです。

**Comment by YamajiTomoya** [comment]
修正いたしました！

**Comment by YamajiTomoya** [comment]
どうやらまた汚くなってしまっているようです。
修正完了したら報告いたします。

**Comment by YamajiTomoya** [comment]
rubocopを導入しました。
修正できてるはずです！
https://github.com/YamajiTomoya/BlogSystem/commit/caa4c5edd40a5548b4da5902026145b0643e8a52

**Comment by Kta-M** [comment]
👍
