### ISSUE TITLE
確認用パスワードの一致判定はモデルでやろう。

### ISSUE THREAD

**Issue by Kta-M** [YamajiTomoya/BlogSystem#22]
このあたりの判定をモデルのバリデーションに持たせるとスタイリッシュ。
https://github.com/YamajiTomoya/BlogSystem/blob/master/app/controllers/users_controller.rb#L26

**Comment by YamajiTomoya** [comment]
修正いたしました！

**Comment by Kta-M** [comment]
devise入れたら自分でやる必要なくなったかな。
