### ISSUE TITLE
user_signed_in?を利用しましょう。

### ISSUE THREAD

**Issue by nmbakfm** [YamajiTomoya/BlogSystem#31]
viewのaritcles/show.html.erbの`if current_user`は`if user_signed_in?`で置き換えられます。
暗黙のキャストがあるので、どちらでも同じですが、なるべくtrue/falseをifの条件式に使ってあげましょう。
このくらいシンプルなシステムであれば、大丈夫ですが、複雑なシステムを作るときには可読性が下がってしまいます。

**Comment by YamajiTomoya** [comment]
かしこまりました。
修正済みです！
https://github.com/YamajiTomoya/BlogSystem/commit/bd9e99f44a9207cbf0d6cff8390d3720dde93513

**Comment by nmbakfm** [comment]
OKです
