### ISSUE TITLE
solargraphをGemfileに入れるのはやめよう

### ISSUE THREAD

**Issue by ippachi** [YamajiTomoya/BlogSystem#37]
solargraphはエディタのためのgemなのでプロジェクトメンバー全員が入れる必要がないです
なので普通に `gem install` でいれるか `Gemfile.local` などの個人用Gemfileを作成していれよう

**Comment by YamajiTomoya** [comment]
修正しましたっ！
https://github.com/YamajiTomoya/BlogSystem/commit/9e943d51c70eb45a83bd8752a147daea109290ed

**Comment by ippachi** [comment]
👍
