### ISSUE TITLE
Associationsを使ってみよう

### ISSUE THREAD

**Issue by ippachi** [YamajiTomoya/BlogSystem#38]
https://github.com/TsuMakoto/blog-system/issues/6

**Comment by YamajiTomoya** [comment]
修正しましたっ！
見落としあったらごめんなさい
https://github.com/YamajiTomoya/BlogSystem/commit/d2656b0366af7ac059ca8750c6c3fe2b6b28890f

**Comment by Kta-M** [comment]
https://github.com/YamajiTomoya/BlogSystem/blob/master/app/controllers/articles_controller.rb#L24
ここも、
```
current_user.articles.build(article_params)
```
にできるよ。

**Comment by Kta-M** [comment]
https://github.com/YamajiTomoya/BlogSystem/blob/master/app/controllers/articles_controller.rb#L7-L9
```
    @search = @user.articles.ransack(params[:q])
    @articles = @search.result.order(:id).page(params[:page]).per(3)
```

**Comment by Kta-M** [comment]
https://github.com/YamajiTomoya/BlogSystem/blob/master/app/controllers/comments_controller.rb#L5

**Comment by YamajiTomoya** [comment]
修正いたしました！
https://github.com/YamajiTomoya/BlogSystem/commit/5e8e72154948cd00ec3654a0631f793daac36c23

**Comment by Kta-M** [comment]
👍

**Comment by ippachi** [comment]
👍
