### ISSUE TITLE
DBをPostgreSQLにしてみよう

### ISSUE THREAD

**Issue by Kta-M** [YamajiTomoya/BlogSystem#39]
扱いが他のDBに比べてカンタンなので標準でsqlite3が使われるようになっていますが、
普通は本番環境と同じDBを使います。

FusicではPostgreSQL or MySQLにすることが多いです。
今回はPostgreSQLを使ってみましょう。

**Comment by YamajiTomoya** [comment]
修正いたしました！
https://github.com/YamajiTomoya/BlogSystem/commit/139eb98456ce91369300d3acfc2f704cbdb41e8e

**Comment by Kta-M** [comment]
はやっｗ
