### ISSUE TITLE
複数あるときは増やす場合を考えよう

### ISSUE THREAD

**Issue by Kta-M** [YamajiTomoya/BlogSystem#40]
コレのことなんだけど、
https://github.com/YamajiTomoya/BlogSystem/blob/master/app/assets/javascripts/form_reset.js#L3
リセットするべきフォームが増えたとき、ひとつずつidを足していくのか…と考えたらちょっと面倒。編集するファイルも2つだし。
と考えたら、classで指定しよう、となる。

ここに限らず、同じものが複数あるときは増やすときを想像すると、自然と共通化の流れになって吉。

**Comment by YamajiTomoya** [comment]
ファイルをもう一度見直して、記事の更新部もうまくできそうだったのでやってみました。
一応全て確認いたしましたが、もし見落としがあればすみません。
https://github.com/YamajiTomoya/BlogSystem/commit/deddb35bca9a86a283a3bd31f07f98c40cce94e4

**Comment by Kta-M** [comment]
articles_controllerのupdateの変更って何をしてるんだろう？ 🤔

**Comment by YamajiTomoya** [comment]
えっと、「入力に失敗した場合には（空のデータを送信した場合は）、失敗した場所を最初に持っていた値を差し込むのですが、そのままだと『title: 空, content: 編集済み』が『title:初期値, content: 初期値』のように、編集をした部分まで初期値に戻ってしまうので、『title: 空, content: 編集済み』→『title: 初期値, content: 編集済み』のようになるようにしています。

**Comment by YamajiTomoya** [comment]
@checkも保存されてしまっていた問題を修正しました。https://github.com/YamajiTomoya/BlogSystem/commit/9f3a265e52fe5867fb8407be8d3670b1b74c894f
（updateはsaveを呼んでいるのですね）

**Comment by Kta-M** [comment]
> updateはsaveを呼んでいるのですね

そうっすねー。
Qiitaのレイアウトが変わって読みにくくなってるけどコレが便利。
https://qiita.com/tyamagu2/items/8abd93bb7ab0424cf084

結局、ここのactionってこんなに複雑にしないといけないんだっけ？

**Comment by YamajiTomoya** [comment]
見過ごしていました。（RecentlyUpdateddでソートすべきですね。。。）
記事ありがとうございます。

普通の方法でやってみたんですが、どうにもやりたいことが実現できなかったのでそのままにすることにしました。
記入途中のをそのまま残す→@articleに値のみ差し込んでrender→nilもそのまま表示されてしまう（ただし保存はできない）になっしまうため、
@articleに値のみ差し込む→nilの差し込みはしない→nilでないもののみ@articleに入れてしまうと、バリデーションを通ってしまう→@checkに一回入れて、saveできるか（バリデーションを通るか）チェック

と考えているのですが、いかがでしょうか？

**Comment by Kta-M** [comment]
内容が空でバリデーションに引っかかった場合、内容を復元したいわけね。りょうかーい。
今回はそこまで求めないけど、Model側でカラムになにか設定したら自動でこうなるようになるとかっこいいね。
