### ISSUE TITLE
何かを管理する場所はできるだけ一つにまとめよう

### ISSUE THREAD

**Issue by Kta-M** [YamajiTomoya/BlogSystem#41]
コレのことなんだけど、
https://github.com/YamajiTomoya/BlogSystem/blob/master/app/assets/javascripts/header_menu_effect.js
jsでcssのお世話をしてる。cssは普通cssファイルで指定するので、他の人や将来の自分が全体的にcssの調整をするときに対応漏れしたり、ここのcssを調整するときに探すのに手間取ったりするかも。
となると、cssはやっぱりcssファイルに任せて、jsでclassの付け替えをすることでcssを適用しよう、となる。

コレに限らず、何かを管理する場所はできるだけ一つにまとめたほうがいいし、それぞれ何を管理しているのか(何の役割がメインなのか)を考えると吉。

**Comment by YamajiTomoya** [comment]
かしこまりました！
今回は、css内で完結できそうだったので、当該のjsファイルは削除することにしました。
https://github.com/YamajiTomoya/BlogSystem/commit/1fdba27c1af1012355a488df6a080e7618c104b4

**Comment by Kta-M** [comment]
そうねー、たしかに👍
