### ISSUE TITLE
domを複数回取得する場合は変数に入れよう

### ISSUE THREAD

**Issue by Kta-M** [YamajiTomoya/BlogSystem#42]
https://github.com/YamajiTomoya/BlogSystem/blob/master/app/assets/javascripts/search_box_acordion.js
これ、毎回domの検索が走っています。変数に入れましょう。

**Comment by YamajiTomoya** [comment]
修正いたしました。先ほどはありがとうございました！
https://github.com/YamajiTomoya/BlogSystem/commit/02238f8116378f5c455e07b91e62ed24f6657b11

**Comment by Kta-M** [comment]
👍
