### ISSUE TITLE
scssを活用しよう

### ISSUE THREAD

**Issue by Kta-M** [YamajiTomoya/BlogSystem#43]
scssファイルを見るとほぼ普通のcssになってるので、せっかくならscssの機能を活用しよう。
https://dev.classmethod.jp/slide/scss-tutorial/

> 3.2，すぐに使える

にあるように、ネストを使うだけでもとても便利！

**Comment by YamajiTomoya** [comment]
とりあえずネストを使ってみました。
とても便利です。。。！
https://github.com/YamajiTomoya/BlogSystem/commit/185601454a072925d5ca446b70e7ad76be92b993

**Comment by Kta-M** [comment]
👍
