### ISSUE TITLE
後置ifは節度を持って使おう

### ISSUE THREAD

**Issue by Kta-M** [YamajiTomoya/BlogSystem#44]
https://github.com/YamajiTomoya/BlogSystem/blob/master/app/controllers/articles_controller.rb#L63

変に使うと読みづらくなるので。
https://qiita.com/jnchito/items/4e47559a4c821474233a

**Comment by YamajiTomoya** [comment]
修正いたしました！どうやらrubocopが余計な気遣いをしてくれていたようです。
後置にすべきでないところを毎回修正していくのか、後置にした方が読みやすいところを毎回自分でそのようにするのか、を天秤に掛けて、後者を選ぶことにしました。
https://github.com/YamajiTomoya/BlogSystem/commit/2e10da09627045fdc3d81da4bb55358ed99b68a1

**Comment by Kta-M** [comment]
👍
