### ISSUE TITLE
部分テンプレートを使ってみよう

### ISSUE THREAD

**Issue by Kta-M** [YamajiTomoya/BlogSystem#51]
articleのeditとnewに使えるはず
https://qiita.com/shizuma/items/1c655dadd2e04b3990a8

**Comment by YamajiTomoya** [comment]
修正いたしました！便利です！
https://github.com/YamajiTomoya/BlogSystem/commit/bb489090a6541d29fa817b0aa0d85d56d75fa656

**Comment by Kta-M** [comment]
👍
