### ISSUE TITLE
strong_parameterを利用しましょう。

### ISSUE THREAD

**Issue by nmbakfm** [YamajiTomoya/BlogSystem#6]
`Rails strong parameter`とかで検索すると、`require`とか`permit`に関する記述が出てくると思うので、参考にしてください。

**Comment by YamajiTomoya** [comment]
一応、strong_parameterの設定だけ修正しました。
ルーティングに関しては別でissueを立てておきます。
https://github.com/YamajiTomoya/BlogSystem/commit/7f1666fa4402e802b2a0e6fc3fd52edfbd164762
https://github.com/YamajiTomoya/BlogSystem/commit/7f1666fa4402e802b2a0e6fc3fd52edfbd164762

**Comment by nmbakfm** [comment]
ミマシタ
